cozinha/urls.py
from django.urls import path
from . import views

app_name = "cozinha"

urlpatterns = [
    # Uma rota é um caminho para uma página que você acesssa através de uma URL
    # Rotas para acessar funções dos produtos
    path('produtos', views.ProductListView.as_view(), name='products'),      # Listar produto
    path('produtos/comidas', views.ComidasListView.as_view(), name='products-com'),      # Listar produto
    path('produtos/bebidas', views.BebidasListView.as_view(), name='products-beb'),      # Listar produto
    path('produtos/sobremesas', views.SobremesasListView.as_view(), name='products-sob'),      # Listar produto
    path('produtos/criar', views.ProductCreateView.as_view(), name='product-add'),       # Criar produto
    path('produtos/editar/<int:pk>', views.ProductUpdateView.as_view(), name='product-edit'),        # Editar produto
    # path('produtos/deletar/<int:pk>', views.ProductDeleteView.as_view(), name='product-delete'),     # Deletar produto
    path('produtos/detalhes/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),        # Visualizar detalhas do produto
    path('produtos/desativar/<int:pk>', views.ProductDisableView.as_view(), name='product-disable'),     # Desativar produto

    # Rotas para acessar funções das mesas
    path('mesas', views.TableListView.as_view(), name='tables'),       # Listar mesa
    path('mesas/criar', views.TableCreateView.as_view(), name='table-add'),      # Criar mesa
    path('mesas/editar/<int:pk>', views.TableUpdateView.as_view(), name='table-edit'),       # Editar mesa
    # path('mesas/deletar/<int:pk>', views.TableDeleteView.as_view(), name='table-delete'),        # Deletar mesa
    path('mesas/detalhes/<int:pk>', views.TableDetailView.as_view(), name='table-detail'),       # Visualizar detalhas da mesa
    path('mesas/desativar/<int:pk>', views.TableDisableView.as_view(), name='table-disable'),        # Desativar mesa
]

mysite/urls.py
"""
    Este script faz o controle do funcionamento das urls do site
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # administração do django
    path('admin/', admin.site.urls),
    # autenticação de usuários
    path('accounts/', include('allauth.urls')),
    path("", include("pages.urls", namespace="pages")),
    # aplicativo da cozinha
    path('cozinha/', include('cozinha.urls')),  
    # aplicativo dos clientes    # o método include() busca n
    path('clientes/', include('clientes.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

cozinha/models.py
from statistics import mode
from django.db import models
from django.urls import translate_url

# Create your models here.
class Product(models.Model):
    CHOICES_TYPES = (
        (1, 'comidas'),
        (2, 'bebidas'),
        (3, 'sobremesas')
    )
    name = models.CharField(verbose_name='Nome do produto', max_length=100)
    type = models.IntegerField(verbose_name='Tipo do produto', choices=CHOICES_TYPES, default=1)
    value = models.CharField(verbose_name='Valor do produto', max_length=8)
    image = models.ImageField(verbose_name='Imagem do produto', upload_to='images/')
    description = models.CharField(verbose_name='Descrição do produto', max_length=500)
    is_active = models.BooleanField(verbose_name='Está ativo?', default=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return self.name

class Table(models.Model):
    number = models.IntegerField(verbose_name='Número da mesa')
    seaters = models.IntegerField(verbose_name='Número de assentos')
    details = models.CharField(verbose_name='Detalhes da mesa', max_length=500)
    is_active = models.BooleanField(verbose_name='Está ativa?', default=True)
    is_busy = models.BooleanField(verbose_name="Está ocupada?", default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.number)

cozinha/forms.py
from django import forms
from datetime import datetime
from .models import Product, Table

class ProductForm(forms.ModelForm):
    CHOICES_TYPES = (
        (1, 'comidas'),
        (2, 'bebidas'),
        (3, 'sobremesas')
    )
    type = forms.ChoiceField(choices=CHOICES_TYPES, label='tipo do produto')

    class Meta:
        model = Product
        fields = ('image', 'name', 'value', 'description')
        labels = {'image': 'Imagem do produto', 'name': 'Nome do produto', 'value': 'Preço', 'description': 'Descrição do produto'}

    def __init__(self, *args, **kwargs):
        # user = kwargs.pop('user', None)
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ('number', 'seaters', 'details')
        labels = {'number': 'Número da mesa', 'seaters': 'Número de assentos', 'details': 'Detalhes da mesa e/ou posição'}

    def __init__(self, *args, **kwargs):
        # user = kwargs.pop('user', None)
        super(TableForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

cozinha/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Product, Table
from .forms import ProductForm, TableForm
from django.urls import reverse
class ProductListView(ListView):
    """
        View para a listagem de produtos existentes.
    """

    model = Product
    template_name = 'cozinha/products/list_view.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True).order_by('name')
        return queryset
        return queryset


class ComidasListView(ListView):
    """
        View para a listagem de produtos existentes.
    """

    model = Product
    template_name = 'cozinha/products/list_view/list_comidas.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(is_active=True, type=1)
        return context

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True).order_by('name')
        return queryset

    
class BebidasListView(ListView):
    """
        View para a listagem de produtos existentes.
    """

    model = Product
    template_name = 'cozinha/products/list_view/list_bebidas.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(is_active=True)
        return context

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True).order_by('name')


class SobremesasListView(ListView):
    """
        View para a listagem de produtos existentes.
    """

    model = Product
    template_name = 'cozinha/products/list_view/list_sobremesas.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(is_active=True, type=3)
        return context

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True).order_by('name')
        return queryset


class ProductUpdateView(UpdateView):
    """
        View para alteração das informações de um produto existente.
    """

    model = Product
    form_class = ProductForm
    template_name = 'cozinha/products/update_view.html'

    def get_form_kwargs(self):
        kwargs = super(ProductUpdateView, self).get_form_kwargs()
        return kwargs

    def get_success_url(self):
        return reverse("cozinha:products")
class ProductDisableView(DeleteView):
    """
        View para deletar um produto existente.
    """

    model = Product
    template_name = 'cozinha/products/disable_view.html'

    def get_object(self):
        obj = super(ProductDisableView, self).get_object()
        if not obj.is_active:
            raise Http404
        return obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse("cozinha:products")

class ProductCreateView(CreateView):
    """
        View para criação de um produto.
    """

    model = Product
    form_class = ProductForm
    template_name = 'cozinha/products/create_view.html'

    def get_form_kwargs(self):
        kwargs = super(ProductCreateView, self).get_form_kwargs()
        # org_obj = self.request.user.selected_organization
        # kwargs['org_obj'] = org_obj
        return kwargs

    def form_valid(self, form):
        # form.instance.organization = self.request.user.selected_organization
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("cozinha:products")

class ProductDetailView(DetailView):
    """
        View para exibir detalhes de um produto existente.
    """
    model = Product
    template_name = 'cozinha/products/detail_view.html'

    def get_object(self):
        obj = super(ProductDetailView, self).get_object()
        if not obj.is_active:
            raise Http404
        return obj

    def get_success_url(self):
        return reverse("cozinha:products")

class TableListView(ListView):
    """
        View para a listagem de mesas existentes.
    """

    model = Table
    template_name = 'cozinha/tables/list_view.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Tables = Table.objects.filter(is_active=True)
        return context

    def get_queryset(self):
        queryset = Table.objects.filter(is_active=True).order_by('number')
        return queryset
class TableUpdateView(UpdateView):
    """
        View para alteração das informações de um produto existente.
    """

    model = Table
    form_class = TableForm
    template_name = 'cozinha/tables/update_view.html'

    def get_form_kwargs(self):
        kwargs = super(TableUpdateView, self).get_form_kwargs()
        return kwargs

    def get_success_url(self):
        return reverse("cozinha:tables")
class TableDisableView(DeleteView):
    """
        View para deletar uma mesa existente.
    """

    model = Table
    template_name = 'cozinha/tables/disable_view.html'

    def get_object(self):
        obj = super(TableDisableView, self).get_object()
        if not obj.is_active:
            raise Http404
        return obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse("cozinha:tables")

class TableCreateView(CreateView):
    """
        View para criação de uma mesa.
    """

    model = Table
    form_class = TableForm
    template_name = 'cozinha/tables/create_view.html'

    def get_form_kwargs(self):
        kwargs = super(TableCreateView, self).get_form_kwargs()
        return kwargs

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("cozinha:tables")
class TableDetailView(DetailView):
    """
        View para exibir detalhes de uma mesa existente.
    """
    model = Table
    template_name = 'cozinha/tables/detail_view.html'

    def get_object(self):
        obj = super(TableDetailView, self).get_object()
        if not obj.is_active:
            raise Http404
        return obj

    def get_success_url(self):
        return reverse("cozinha:tables")

cozinha/templates/cozinha/products/create_view.html
{% extends "base.html" %}

{% block title %}{{ request.site.name }} - RH{% endblock %}

{% load crispy_forms_tags %}

{% block titlebody %}Gestão de Pessoas{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <!-- left column -->
  <div class="col-md-10">
    <!-- general form elements -->
    <div class="card card-outline card-primary">
      <div class="card-header">
        <h3 class="card-title">Criar novo produto</h3>
        <a class="btn btn-sm btn-outline-primary float-right" href="{% url 'cozinha:products' %}">Voltar</a>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form method="post" enctype="multipart/form-data">
        <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Criar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

cozinha/templates/cozinha/products/delete_view.html
{% extends "base.html" %}

{% block title %}Excluir Produto{% endblock %}

{% block content %}
  <div class="container page-config">
    <div class="intro-text">
      <h2 class="mb-3">Confirmar Exclusão</h2>
      <p class="lead">Tem certeza que deseja excluir o produto <strong>"{{ object.name }}"</strong>? Todas os dados do histórico serão excluídos.</p>
      <p class="lead">
      <form method="post">
        {% csrf_token %}
        <br><br>
        <button type="submit" class="btn btn-danger">Sim, tenho certeza</button>
        <a href="{% url 'cozinha:products' %}" class="btn btn-outline-secondary" role="button">Cancelar</a>
      </form>
      </p>
    </div>
  </div>
{% endblock %}

cozinha/templates/cozinha/products/detail_view.html
{% extends 'base.html' %}

{% block title %}{{ request.site.name }} - Perfil{% endblock %}

{% block titlebody %}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class=" col-md-10">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">Detalhes da Indicação</h3>
                <a class="btn-sm btn-white float-right" href="{% url 'cozinha:produtos' %}">Voltar</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body flex">
                <div class="table-responsive">
                    <!-- <table class="table table-sm table-bordered">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Cargo anterior</th>
                                <th>Novo cargo</th>
                                <th>Indicado por</th>
                                <th>Indicado em</th>
                                {% if not object.promotion_status == '4' %}
                                    <th>Avaliada por</th>
                                    <th>Avaliada em</th>
                                {% else %}
                                    <th>Expirada em</th>
                                {% endif %}
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ object.employee.name }}</td>
                                <td>{{ object.previous_sub_title }}</td>
                                <td>{{ object.new_sub_title }}</td>
                                <td>{{ object.indicated_by.full_name }}</td>
                                <td>{{ object.created_at }}</td>
                                {% if not object.promotion_status == '4' %}
                                    <td>{{ object.evaluated_by.full_name }}</td>
                                {% endif %}
                                <td>{{ object.updated_at }}</td>
                                <td>{{ object.get_promotion_status_display }}</td>
                            </tr>
                        </tbody>
                    </table> -->
                </div>
                {% if object.comment %}
                    <label for="comment">Comentário da indicação:</label>
                    <div id="comment" class="info-box bg-light">
                        <div class="info-box-content m-1 responsible">
                            <span class="info-box-text text-wrap mb-0">{{ object.comment }}</span>
                        </div>
                    </div>
                {% endif %}
                {% if object.comment_reverse and not object.promotion_status == '4' %}
                    <label for="comment-reverse">Comentário da avaliação:</label>
                    <div id="comment-reverse" class="info-box bg-light">
                        <div class="info-box-content">
                            <span class="info-box-text text-wrap mb-0">{{ object.comment_reverse }}</span>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

cozinha/templates/cozinha/products/disable_view.html
{% extends "base.html" %}

{% block title %}Desativar Produto{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <!-- left column -->
    <div class="col-md-10">
        <!-- general form elements -->
        <div class="card card-outline card-primary">
            <div class="card-header">
                <h3 class="card-title">Confirmar Desativação</h3>
                <a class="btn btn-sm btn-outline-primary float-right" href="{% url 'cozinha:products' %}">Voltar</a>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post">
                <div class="card-body">
                    <p class="lead">Tem certeza que deseja desativar o produto <strong>"{{ object.name }}"</strong>?</p>
                    {% csrf_token %}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-danger">Sim, tenho certeza</button>
                    <a href="{% url 'cozinha:products' %}" class="btn btn-outline-secondary" role="button">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

cozinha/templates/cozinha/products/list_view.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ request.site.name }} {% endblock %}

{% block titlebody %}{% endblock %}

{% block extrahead %} 
    <link rel="stylesheet" href="{% static 'css/list_products.css' %}">
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class=" col-md-10">
        <div class="card card-outline card-primary">
            <div class="card-header">
                <h3 class="card-title">Produtos</h3>
                <a class="btn btn-sm btn-outline-primary" href="{% url 'cozinha:product-add' %}"
                    style="float: right;"><i class="fas fa-user-plus"></i>Criar novo produto</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div>
                        <form method="GET">
                            <div class="row justify-content-around float-right">
                                <div class="col-md-4">
                                    <input type="checkbox" name="finished" id="finished" {% if 'finished' in request.GET %}
                                        checked {% endif %}>
                                    <label for="finished">Exibir produtos desativados</label>
                                </div>
                                <div class="col-md-4 d-flex justify-content-center float-right">
                                    <input type="text" class="form-control" placeholder="Pesquisar" name='text'
                                        id="text-search" aria-label="Username" aria-describedby="basic-addon1"
                                        value="{{ request.GET.text }}">
                                    <button class="btn-sm btn-primary col-md-3 float-right" type="submit"
                                        name="action">Buscar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <hr>
                <ul class="product-container row justify-content-around">
                    <li class="col-md-10 text-center">
                        <a href="{% url 'cozinha:products-com' %}"><h1>Comidas</h1></a>
                    </li>
                    <li class="col-md-10 text-center">
                        <a href="{% url 'cozinha:products-beb' %}"><h1>Bebidas</h1></a>
                    </li>
                    <li class="col-md-10 text-center">
                        <a href="{% url 'cozinha:products-sob' %}"><h1>Sobremesas</h1></a>
                    </li>
                </ul>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cozinha/templates/cozinha/products/update_view.html
{% extends 'base.html' %}

{% block title %}{{ request.site.name }} {% endblock %}

{% load crispy_forms_tags %}

{% block titlebody %}título{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <!-- left column -->
    <div class="col-md-10">
        <!-- general form elements -->
        <div class="card card-outline card-primary">
            <div class="card-header">
                <h3 class="card-title">Editar produto: {{ object.name }}</h3>
                <a class="btn btn-sm btn-outline-primary float-right" href="{% url 'cozinha:products' %}">Voltar</a>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Alterar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}