cozinha/urls.py
from django.urls import path
from . import views

app_name = "cozinha"

urlpatterns = [
    # Uma rota é um caminho para uma página que você acesssa através de uma URL
    # Rotas para acessar funções dos produtos
    path('produtos', views.ProductListView.as_view(), name='products'),      # Listar produto
    path('produtos/comidas', views.ComidasListView.as_view(), name='products-com'),      # Listar produto
    path('produtos/bebidas', views.BebidasListView.as_view(), name='products-beb'),      # Listar produto
    path('produtos/sobremesas', views.SobremesasListView.as_view(), name='products-sob'),      # Listar produto
    path('produtos/criar', views.ProductCreateView.as_view(), name='product-add'),       # Criar produto
    path('produtos/editar/<int:pk>', views.ProductUpdateView.as_view(), name='product-edit'),        # Editar produto
    # path('produtos/deletar/<int:pk>', views.ProductDeleteView.as_view(), name='product-delete'),     # Deletar produto
    path('produtos/detalhes/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),        # Visualizar detalhas do produto
    path('produtos/desativar/<int:pk>', views.ProductDisableView.as_view(), name='product-disable'),     # Desativar produto

    # Rotas para acessar funções das mesas
    path('mesas', views.TableListView.as_view(), name='tables'),       # Listar mesa
    path('mesas/criar', views.TableCreateView.as_view(), name='table-add'),      # Criar mesa
    path('mesas/editar/<int:pk>', views.TableUpdateView.as_view(), name='table-edit'),       # Editar mesa
    # path('mesas/deletar/<int:pk>', views.TableDeleteView.as_view(), name='table-delete'),        # Deletar mesa
    path('mesas/detalhes/<int:pk>', views.TableDetailView.as_view(), name='table-detail'),       # Visualizar detalhas da mesa
    path('mesas/desativar/<int:pk>', views.TableDisableView.as_view(), name='table-disable'),        # Desativar mesa
]

mysite/urls.py
"""
    Este script faz o controle do funcionamento das urls do site
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # administração do django
    path('admin/', admin.site.urls),
    # autenticação de usuários
    path('accounts/', include('allauth.urls')),
    path("", include("pages.urls", namespace="pages")),
    # aplicativo da cozinha
    path('cozinha/', include('cozinha.urls')),  
    # aplicativo dos clientes    # o método include() busca n
    path('clientes/', include('clientes.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    {% block extrahead %}{% endblock %}
    {% block initialscripts %}{% endblock %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Bar do Ailtinho</a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:products' %}">Produtos</a>
                    </li>
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:product-add' %}">Adicionar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:product-edit' %}">editar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:product-detail' %}">detalhes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:product-disable' %}">desabilitar</a>
                    </li> {% endcomment %}
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:tables' %}">Mesas</a>
                    </li>
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:table-add' %}">Adicionar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:table-edit' %}">editar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:table-detail' %}">detalhes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cozinha:table-disable' %}">desabilitar</a>
                    </li> {% endcomment %}

                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block finalscripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Bar do Ailtinho - Página Inicial{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <!-- left column -->
        <div class="col-md-10">
            <!-- general form elements -->
            <div class="card card-outline card-primary">
                <div class="card-header text-center">
                    <h3 class="card-title">SEJAM BEM VINDOS!</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-dark m-1">Iniciar sessão</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/sobre.html
{% extends 'base.html' %}

{% block title %}Bar do Ailtinho - Sobre{% endblock %}

{% block content %}
    <h1>Sobre nós</h1>
    <p>O bar do Ailtinho é dedicado a oferecer os melhores produtos e o melhor atendimento</p>
{% endblock %}